[build-system]
requires = [
    "setuptools >= 40.9.0",
    "wheel"
]
build_backend = "setuptools.build_meta"

[tool.mypy]
python_version = 3.12
strict=true

[tool.ruff]
line-length = 79
indent-width = 4
target-version = "py312"
