name: "Test and build wtime"

on: 
  push:
    branches:
      - "**"

jobs:
  linters: 
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.1
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.1"
    - name: Install deps
      run: |
        python3 -m pip install -U pip
        pip install ".[dev]"
    - name: Run linters
      run: |
        mypy wtime tests
        pylint wtime tests
  test:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python: ["3.10", "3.9", "3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python matrix
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Run tests
      run: |
        python3 -m unittest tests/test_wtime.py
    